import json

from graft_plus.completeness import audit
from graft_plus.graph import build_graph


def _boundary(graph, kind, source):
    return [
        row
        for row in graph["facts"]["relationship_boundaries"]
        if row["kind"] == kind and row["source"] == source
    ]


def test_python_runtime_boundaries_are_source_and_line_backed(tmp_path):
    (tmp_path / "app.py").write_text(
        "from plugins import *\n"
        "import importlib\n"
        "plugin = importlib.import_module(plugin_name)\n"
        "db = Depends(get_db)\n"
        "app.include_router(router, prefix='/v1')\n"
    )

    graph = build_graph(subject=tmp_path)

    wildcard = _boundary(graph, "wildcard_import", "app.py")
    dynamic = _boundary(graph, "dynamic_load", "app.py")
    injection = _boundary(graph, "dependency_injection", "app.py")
    routes = _boundary(graph, "route_composition", "app.py")
    assert [row["line"] for row in wildcard] == [1]
    assert [row["line"] for row in dynamic] == [3]
    assert [row["line"] for row in injection] == [4]
    assert [row["line"] for row in routes] == [5]
    assert dynamic[0]["status"] == "unresolved"
    assert routes[0]["status"] == "declared"


def test_javascript_dynamic_di_and_route_composition_boundaries(tmp_path):
    (tmp_path / "app.js").write_text(
        "const plugin = import(pluginName)\n"
        "const service = container.resolve(token)\n"
        "app.use('/admin', adminRouter)\n"
        "// import(commentOnly)\n"
    )

    graph = build_graph(subject=tmp_path)

    assert [row["line"] for row in _boundary(graph, "dynamic_load", "app.js")] == [1]
    assert [row["line"] for row in _boundary(graph, "dependency_injection", "app.js")] == [2]
    assert [row["line"] for row in _boundary(graph, "route_composition", "app.js")] == [3]


def test_fixture_code_remains_visible_but_embedded_source_strings_do_not(tmp_path):
    fixture = tmp_path / "tests" / "fixtures"
    fixture.mkdir(parents=True)
    (fixture / "loader.js").write_text(
        "main(require(resolve(process.argv[2])))\n"
        '"example": "require(dynamicName)"\n'
    )

    graph = build_graph(subject=tmp_path)

    assert [row["line"] for row in _boundary(graph, "dynamic_load", "tests/fixtures/loader.js")] == [1]


def test_jvm_wildcard_import_is_an_explicit_boundary(tmp_path):
    (tmp_path / "App.java").write_text("import com.example.plugins.*;\nclass App {}\n")

    graph = build_graph(subject=tmp_path)

    wildcard = _boundary(graph, "wildcard_import", "App.java")
    assert [row["line"] for row in wildcard] == [1]
    assert wildcard[0]["status"] == "unresolved"


def test_generated_build_and_contract_inputs_are_visible(tmp_path):
    (tmp_path / "generated.py").write_text(
        "# generated header art\n"
        "# second header line\n"
        "# third header line\n"
        "# fourth header line\n"
        "# fifth header line\n"
        "# Code generated by protoc. DO NOT EDIT.\n"
        "VALUE = 1\n"
    )
    (tmp_path / "schema.proto").write_text('syntax = "proto3";\nmessage User {}\n')
    (tmp_path / "package.json").write_text(
        json.dumps(
            {
                "name": "boundary-fixture",
                "scripts": {"generate": "protoc schema.proto"},
            },
            indent=2,
        )
    )
    (tmp_path / "tsconfig.json").write_text(
        json.dumps({"compilerOptions": {"paths": {"@app/*": ["src/*"]}}}, indent=2)
    )

    graph = build_graph(subject=tmp_path)

    contract = next(node for node in graph["nodes"] if node["id"] == "file:schema.proto")
    assert contract["type"] == "contract_source"
    assert _boundary(graph, "generated_source", "generated.py")
    assert _boundary(graph, "code_generation", "package.json")
    assert _boundary(graph, "build_module_mapping", "tsconfig.json")


def test_boundary_summary_reaches_completeness_without_adjudication(tmp_path):
    (tmp_path / "app.py").write_text("plugin = __import__(name)\n")

    graph = build_graph(subject=tmp_path)
    completeness = audit(graph, subject=tmp_path)

    assert graph["schema_version"] == "1.9"
    assert graph["metrics"]["unresolved_relationship_boundary_count"] == 1
    assert completeness["residuals"]["relationship_boundary_counts_by_kind"] == {
        "dynamic_load": 1
    }
    assert completeness["residuals"]["unresolved_relationship_boundary_count"] == 1
    assert "decision" not in completeness


def test_boundary_rows_are_deterministic_and_do_not_create_edges(tmp_path):
    (tmp_path / "plugin.js").write_text("const loaded = require(moduleName)\n")

    first = build_graph(subject=tmp_path)
    second = build_graph(subject=tmp_path)

    assert first["facts"]["relationship_boundaries"] == second["facts"]["relationship_boundaries"]
    assert first["edges"] == second["edges"]
    # The unresolved dynamic load still must not invent a dependency edge.
    assert not any(edge["type"] in {"imports", "imports_package", "invokes", "sources"} for edge in first["edges"])
    assert any(edge["type"] == "member_of_subsystem" for edge in first["edges"])
    ids = {node["id"] for node in first["nodes"]}
    assert all(edge["from"] in ids and edge["to"] in ids for edge in first["edges"])
