"""Evidence-backed architectural projection above language-specific extractors.

This layer does not invent cross-language dependency edges. It projects facts that
are directly supported by repository structure and control files: subsystem
hierarchy, build inputs, governance boundaries, source provenance, and aggregate
cross-language membership.
"""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from graft_plus.inventory import (
    BUILD_FILES,
    BUILD_SUFFIXES,
    CONTRACT_SUFFIXES,
    GOVERNANCE_FILES,
    SOURCE_SUFFIXES,
    language,
    rel,
    relevant_files,
)

_FILE_LEVEL_TYPES = frozenset(
    {
        "python_module",
        "test_module",
        "javascript_module",
        "shell_module",
        "go_module",
        "go_package",
        "rust_module",
        "ruby_module",
        "php_module",
        "native_module",
        "jvm_module",
        "dotnet_module",
        "lua_module",
        "elixir_module",
        "swift_module",
        "software_package",
        "contract_source",
        "manifest",
        "ci_workflow",
        "docker",
        "migration",
        "source_file",
        "test_file",
        "documentation",
        "configuration",
    }
)

_REFERENCE_SUFFIXES = SOURCE_SUFFIXES | CONTRACT_SUFFIXES
_QUOTED_PATH_RE = re.compile(r"[\"']([^\"']+)[\"']")
_GENERATED_MARKERS = (
    "generated file",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "@generated",
)
_GENERATED_PARTS = frozenset({"gen", "generated", "autogen", "autogenerated"})
_VENDORED_PARTS = frozenset({"third_party", "third-party", "vendor", "vendored", "external"})


def _is_build_file(path: Path) -> bool:
    return path.name in BUILD_FILES or path.suffix.lower() in BUILD_SUFFIXES


def _is_governance_file(path: Path) -> bool:
    return path.name in GOVERNANCE_FILES


def _build_system(path: Path) -> str:
    name = path.name
    suffix = path.suffix.lower()
    if name in {".gn", "BUILD.gn"} or suffix == ".gni":
        return "gn"
    if name in {"BUILD", "BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel", "MODULE.bazel"} or suffix in {".bazel", ".bzl"}:
        return "bazel"
    if name == "CMakeLists.txt" or suffix == ".cmake":
        return "cmake"
    if name in {"Makefile", "GNUmakefile"}:
        return "make"
    if name in {"meson.build", "meson_options.txt"}:
        return "meson"
    if name in {"SConstruct", "SConscript"}:
        return "scons"
    if name in {"pom.xml"}:
        return "maven"
    if name in {"build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"} or suffix == ".gradle":
        return "gradle"
    if suffix in {".csproj", ".fsproj", ".vbproj"}:
        return "msbuild"
    if name in {"Cargo.toml", "Cargo.lock"}:
        return "cargo"
    if name in {"go.mod", "go.sum"}:
        return "go"
    if name in {"package.json", "package-lock.json"}:
        return "npm"
    if name in {"pyproject.toml", "requirements.txt"}:
        return "python"
    if name == "Package.swift":
        return "swiftpm"
    if name == "DEPS":
        return "chromium-deps"
    return "other"


def _governance_kind(path: Path) -> str:
    if path.name in {"OWNERS", "CODEOWNERS"}:
        return "ownership"
    if path.name == "PRESUBMIT.py":
        return "process"
    if path.name == "SECURITY.md":
        return "security"
    return "governance"


def _source_provenance(subject: Path, source: str) -> tuple[str, str]:
    path = subject / source
    parts = {part.lower() for part in Path(source).parts}
    if parts & _GENERATED_PARTS:
        return "generated", "path"
    try:
        prefix = path.read_text(encoding="utf-8", errors="ignore")[:4096].lower()
    except OSError:
        prefix = ""
    if any(marker in prefix for marker in _GENERATED_MARKERS):
        return "generated", "header"
    if parts & _VENDORED_PARTS:
        return "vendored", "path"
    return "authored", "repository"


def _path_value(path: Path) -> str:
    value = path.as_posix().strip("/")
    return value or "."


def _parent_path(value: str) -> str | None:
    if value == ".":
        return None
    parent = Path(value).parent.as_posix()
    return parent if parent not in {"", "."} else "."


def _nearest_subsystem(source: str, subsystem_paths: set[str]) -> str:
    parent = Path(source).parent
    candidates = ["."]
    if parent.as_posix() not in {"", "."}:
        parts = parent.parts
        candidates.extend(Path(*parts[:index]).as_posix() for index in range(1, len(parts) + 1))
    return max((item for item in candidates if item in subsystem_paths), key=lambda item: len(Path(item).parts))


def _representative_source(subsystem: str, controls: list[str], sources: list[str]) -> str:
    exact_controls = [path for path in controls if _path_value(Path(path).parent) == subsystem]
    if exact_controls:
        return sorted(exact_controls)[0]
    prefix = "" if subsystem == "." else subsystem.rstrip("/") + "/"
    candidates = [source for source in sources if subsystem == "." or source.startswith(prefix)]
    return sorted(candidates)[0] if candidates else sorted(controls or sources)[0]


def _preferred_source_nodes(nodes: list[dict[str, Any]]) -> dict[str, list[str]]:
    preferred: dict[str, list[str]] = defaultdict(list)
    for node in nodes:
        source = node.get("source")
        node_type = str(node.get("type") or "")
        if isinstance(source, str) and source and node_type in _FILE_LEVEL_TYPES:
            preferred[source].append(str(node["id"]))
    return {source: sorted(set(ids)) for source, ids in preferred.items()}


def _resolve_build_reference(subject: Path, build_file: Path, raw: str) -> str | None:
    value = raw.strip()
    if not value or ":" in value.removeprefix("//"):
        return None
    candidate = (subject / value[2:]).resolve() if value.startswith("//") else (build_file.parent / value).resolve()
    try:
        relative = candidate.relative_to(subject.resolve())
    except ValueError:
        return None
    if candidate.is_file() and candidate.suffix.lower() in _REFERENCE_SUFFIXES:
        return relative.as_posix()
    return None


def collect_architecture_topology(
    subject: Path,
    existing_nodes: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any], dict[str, dict[str, str]]]:
    subject = subject.resolve()
    files = relevant_files(subject)
    build_files = [path for path in files if _is_build_file(path)]
    governance_files = [path for path in files if _is_governance_file(path)]
    controls = [rel(subject, path) for path in [*build_files, *governance_files]]

    file_level_nodes = [
        node
        for node in existing_nodes
        if str(node.get("type") or "") in _FILE_LEVEL_TYPES
        and isinstance(node.get("source"), str)
        and node.get("source")
    ]
    source_paths = sorted({str(node["source"]) for node in file_level_nodes})
    if not source_paths and not controls:
        return [], [], {
            "subsystem_count": 0,
            "subsystem_direct_member_counts": {},
            "cross_language_subsystem_count": 0,
            "cross_language_subsystems": [],
            "build_definition_count": 0,
            "build_definition_counts_by_system": {},
            "build_input_edge_count": 0,
            "governance_boundary_count": 0,
            "governance_boundary_counts_by_kind": {},
            "source_provenance_counts": {},
        }, {}
    subsystem_paths: set[str] = {"."}
    for source in source_paths:
        parts = Path(source).parts
        if len(parts) > 1:
            subsystem_paths.add(parts[0])
    for control in controls:
        parent = _path_value(Path(control).parent)
        while parent:
            subsystem_paths.add(parent)
            parent = _parent_path(parent)

    architecture_nodes: list[dict[str, Any]] = []
    architecture_edges: list[dict[str, Any]] = []
    for subsystem in sorted(subsystem_paths, key=lambda item: (len(Path(item).parts), item)):
        representative = _representative_source(subsystem, controls, source_paths)
        architecture_nodes.append(
            {
                "id": f"subsystem:{subsystem}",
                "type": "subsystem",
                "source": representative,
                "layer": "generated",
                "path": subsystem,
            }
        )
        parent = _parent_path(subsystem)
        if parent is not None:
            architecture_edges.append(
                {
                    "from": f"subsystem:{subsystem}",
                    "to": f"subsystem:{parent}",
                    "type": "member_of_subsystem",
                    "evidence": representative,
                    "layer": "generated",
                }
            )

    annotations: dict[str, dict[str, str]] = {}
    provenance_by_source: dict[str, tuple[str, str]] = {}
    direct_languages: dict[str, set[str]] = defaultdict(set)
    direct_members: Counter[str] = Counter()
    for node in file_level_nodes:
        source = str(node["source"])
        subsystem = _nearest_subsystem(source, subsystem_paths)
        provenance_by_source.setdefault(source, _source_provenance(subject, source))
        provenance, basis = provenance_by_source[source]
        annotations[str(node["id"])] = {
            "source_provenance": provenance,
            "source_provenance_basis": basis,
            "subsystem": subsystem,
        }
        architecture_edges.append(
            {
                "from": str(node["id"]),
                "to": f"subsystem:{subsystem}",
                "type": "member_of_subsystem",
                "evidence": source,
                "layer": "generated",
            }
        )
        direct_members[subsystem] += 1
        path = subject / source
        lang = language(path)
        if path.suffix.lower() in SOURCE_SUFFIXES and lang != "other":
            direct_languages[subsystem].add(lang)

    source_nodes = _preferred_source_nodes(existing_nodes)
    build_input_edges = 0
    for path in build_files:
        source = rel(subject, path)
        subsystem = _nearest_subsystem(source, subsystem_paths)
        node_id = f"build:{source}"
        architecture_nodes.append(
            {
                "id": node_id,
                "type": "build_definition",
                "source": source,
                "layer": "generated",
                "build_system": _build_system(path),
            }
        )
        architecture_edges.append(
            {
                "from": node_id,
                "to": f"subsystem:{subsystem}",
                "type": "governs_build_of",
                "evidence": source,
                "layer": "generated",
            }
        )
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        seen_targets: set[tuple[str, str]] = set()
        for raw in _QUOTED_PATH_RE.findall(text):
            target_source = _resolve_build_reference(subject, path, raw)
            if not target_source:
                continue
            for target_id in source_nodes.get(target_source, []):
                key = (target_source, target_id)
                if key in seen_targets:
                    continue
                seen_targets.add(key)
                architecture_edges.append(
                    {
                        "from": node_id,
                        "to": target_id,
                        "type": "declares_build_input",
                        "evidence": source,
                        "layer": "generated",
                    }
                )
                build_input_edges += 1

    for path in governance_files:
        source = rel(subject, path)
        subsystem = _nearest_subsystem(source, subsystem_paths)
        node_id = f"governance:{source}"
        architecture_nodes.append(
            {
                "id": node_id,
                "type": "governance_boundary",
                "source": source,
                "layer": "generated",
                "governance_kind": _governance_kind(path),
            }
        )
        architecture_edges.append(
            {
                "from": node_id,
                "to": f"subsystem:{subsystem}",
                "type": "governs_boundary_of",
                "evidence": source,
                "layer": "generated",
            }
        )

    aggregate_languages = {subsystem: set(values) for subsystem, values in direct_languages.items()}
    for subsystem in sorted(subsystem_paths, key=lambda item: len(Path(item).parts), reverse=True):
        parent = _parent_path(subsystem)
        if parent is not None:
            aggregate_languages.setdefault(parent, set()).update(aggregate_languages.get(subsystem, set()))
    cross_language = [
        {"subsystem": subsystem, "languages": sorted(languages)}
        for subsystem, languages in sorted(aggregate_languages.items())
        if len(languages) > 1
    ]
    provenance_counts = Counter(value[0] for value in provenance_by_source.values())
    facts = {
        "subsystem_count": len(subsystem_paths),
        "subsystem_direct_member_counts": dict(sorted(direct_members.items())),
        "cross_language_subsystem_count": len(cross_language),
        "cross_language_subsystems": cross_language,
        "build_definition_count": len(build_files),
        "build_definition_counts_by_system": dict(sorted(Counter(_build_system(path) for path in build_files).items())),
        "build_input_edge_count": build_input_edges,
        "governance_boundary_count": len(governance_files),
        "governance_boundary_counts_by_kind": dict(sorted(Counter(_governance_kind(path) for path in governance_files).items())),
        "source_provenance_counts": dict(sorted(provenance_counts.items())),
    }
    return architecture_nodes, architecture_edges, facts, annotations
